version: "3.5"
services:
  frontend:
    build: ./frontend
    command: yarn start
    depends_on:
      - api
    restart: on-failure
    environment:
      REACT_APP_LOCAL: local
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
  api:
    build: ./api
    command: yarn start
    depends_on:
      - db
    restart: on-failure
    environment:
      LOCAL: local
      TOKEN_SECRET: onlyfordev
      POSTGRES_PASSWORD: onlyfordev
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - ./data/certs:/usr/src/app/data/certs
    ports:
      - "8000:8080"
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: typeormdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: onlyfordev
    ports:
      - "5432:5432"
